# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard.ui'
#
# Created: Wed May  6 17:23:23 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(640, 480)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.lineEdit = QtWidgets.QLineEdit(self.wizardPage1)
        self.lineEdit.setGeometry(QtCore.QRect(150, 30, 241, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.wizardPage1)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 70, 241, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.wizardPage1)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 140, 71, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.wizardPage1)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.wizardPage1)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 140, 171, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.radioButton = QtWidgets.QRadioButton(self.wizardPage1)
        self.radioButton.setGeometry(QtCore.QRect(150, 110, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.wizardPage1)
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setGeometry(QtCore.QRect(150, 140, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label = QtWidgets.QLabel(self.wizardPage1)
        self.label.setGeometry(QtCore.QRect(40, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.wizardPage1)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.wizardPage1)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 110, 71, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.wizardPage1)
        self.pushButton.setGeometry(QtCore.QRect(400, 70, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.wizardPage1)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 110, 171, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.label_4 = QtWidgets.QLabel(self.wizardPage2)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.spinBox = QtWidgets.QSpinBox(self.wizardPage2)
        self.spinBox.setEnabled(True)
        self.spinBox.setGeometry(QtCore.QRect(180, 140, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_5 = QtWidgets.QLabel(self.wizardPage2)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.wizardPage2)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.wizardPage2)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.spinBox_3 = QtWidgets.QSpinBox(self.wizardPage2)
        self.spinBox_3.setEnabled(True)
        self.spinBox_3.setGeometry(QtCore.QRect(180, 220, 42, 22))
        self.spinBox_3.setObjectName("spinBox_3")
        self.comboBox = QtWidgets.QComboBox(self.wizardPage2)
        self.comboBox.setGeometry(QtCore.QRect(180, 50, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.wizardPage2)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 90, 143, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.spinBox_2 = QtWidgets.QSpinBox(self.wizardPage2)
        self.spinBox_2.setEnabled(True)
        self.spinBox_2.setGeometry(QtCore.QRect(180, 180, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_8 = QtWidgets.QLabel(self.wizardPage2)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.wizardPage2)
        self.label_9.setGeometry(QtCore.QRect(10, 140, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.wizardPage2)
        self.label_10.setGeometry(QtCore.QRect(380, 140, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.wizardPage2)
        self.label_11.setGeometry(QtCore.QRect(380, 180, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.wizardPage2)
        self.doubleSpinBox.setGeometry(QtCore.QRect(520, 140, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.wizardPage2)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(520, 180, 62, 22))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.spinBox_4 = QtWidgets.QSpinBox(self.wizardPage2)
        self.spinBox_4.setEnabled(True)
        self.spinBox_4.setGeometry(QtCore.QRect(170, 260, 51, 22))
        self.spinBox_4.setMaximum(10000)
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_12 = QtWidgets.QLabel(self.wizardPage2)
        self.label_12.setGeometry(QtCore.QRect(10, 260, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        Wizard.addPage(self.wizardPage2)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "Wizard"))
        self.pushButton_3.setText(_translate("Wizard", "Download"))
        self.label_3.setText(_translate("Wizard", "Input Source"))
        self.radioButton.setText(_translate("Wizard", "Local"))
        self.radioButton_2.setText(_translate("Wizard", "Web"))
        self.label.setText(_translate("Wizard", "Project name"))
        self.label_2.setText(_translate("Wizard", "Root directory"))
        self.pushButton_2.setText(_translate("Wizard", "Choose File"))
        self.pushButton.setText(_translate("Wizard", "Choose Directory"))
        self.label_4.setText(_translate("Wizard", "Learning Type"))
        self.label_5.setText(_translate("Wizard", "No of Hidden Nodes"))
        self.label_6.setText(_translate("Wizard", "No of Output Nodes"))
        self.label_7.setText(_translate("Wizard", "Choose Learning Rule"))
        self.comboBox.setItemText(0, _translate("Wizard", "Supervised"))
        self.comboBox.setItemText(1, _translate("Wizard", "Unsupervised"))
        self.comboBox_2.setItemText(0, _translate("Wizard", "Perceptron"))
        self.comboBox_2.setItemText(1, _translate("Wizard", "LMS"))
        self.comboBox_2.setItemText(2, _translate("Wizard", "Backpropagation"))
        self.comboBox_2.setItemText(3, _translate("Wizard", "k-Nearest Neighbor"))
        self.label_8.setText(_translate("Wizard", "Neural Network Details"))
        self.label_9.setText(_translate("Wizard", "No of Input Nodes"))
        self.label_10.setText(_translate("Wizard", "Learning Rate"))
        self.label_11.setText(_translate("Wizard", "Momentum Factor"))
        self.label_12.setText(_translate("Wizard", "No of Iteration"))

